# Generated by Django 3.1.1 on 2020-11-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
